
import { GoogleGenAI } from "@google/genai";
import { getSystemPrompts } from './appBuilderService';
import { fetchStudioCookie } from './apiUtils';
import { AppMetadata } from '../types';

/**
 * Returns a configured GoogleGenAI instance.
 * Per @google/genai guidelines, it strictly uses process.env.API_KEY.
 */
export const getAi = async () => {
    // The API key must be obtained exclusively from process.env.API_KEY
    const apiKey = process.env.API_KEY || 'NOT_FOUND';
    
    const href = window.location.href;
    const hostname = window.location.hostname;
    const isStudioMode = href.includes('.goog');
    const isLocal = hostname === 'localhost' || hostname === '127.0.0.1';
    
    /**
     * HumanizeIQ specific: Non-studio modes (deployed apps) route through a proxy
     * for unified access control.
     */
    let baseUrl='https://www.playtest.humanizeiq.ai/api-proxy'
    if (!isStudioMode) {
        baseUrl = `${window.location.origin}/api-proxy`;
    }
    const headers: Record<string, string> = {
        'User-Agent': 'DraftingStudio'
    };
    if (isStudioMode) {
        const cookie = await fetchStudioCookie();
        if (cookie) {
            headers['X-Studio-Cookie'] = cookie;
        }
    }
   
    return new GoogleGenAI({ 
        apiKey: apiKey,
        httpOptions: { 
            baseUrl: baseUrl,
            headers: headers
        }
    });
};

// Cache for system prompts to avoid repeated fetches
let systemPromptsCache: Record<string, string> | null = null;

export const getSystemInstruction = async (key: string): Promise<string> => {
    if (!systemPromptsCache) {
        systemPromptsCache = await getSystemPrompts();
    }
    return systemPromptsCache[key] || '';
};

// FIX: Export geminiService object with methods required by Dashboard component
export const geminiService = {
    /**
     * Generates a welcome greeting based on the application metadata using Gemini.
     */
    getAppContextualGreeting: async (metadata: AppMetadata): Promise<string> => {
        const ai = await getAi();
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: `Generate a short, friendly, and professional one-sentence welcome greeting for an application named "${metadata.name}" which is described as: "${metadata.description}".`,
        });
        return response.text || `Welcome to ${metadata.name}`;
    },
    /**
     * Suggests smart features for the application based on its metadata using Gemini.
     */
    getSmartFeatureIdeas: async (metadata: AppMetadata): Promise<string[]> => {
        const ai = await getAi();
        const response = await ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: `List 3 smart feature ideas for an application named "${metadata.name}" which is described as: "${metadata.description}". Return only the feature names, separated by semicolons.`,
        });
        const text = response.text || "";
        // Extract features from semicolon-separated string generated by the AI
        return text.split(';').map(s => s.trim()).filter(s => s.length > 0);
    }
};